### ISSUE TITLE
failure to create NFT image links

### ISSUE THREAD

**Issue by monsterbitar** [mr-zwets/bcmr-generator#3]
I wanted to update the BCMR for the BLISS tokens, and instead of making a new one by hand I returned to the trusted bcmr-generator, and copy-pasted my old data and did some updates. Then I generated a BCMR file and compared with the old one I had to see what has changed / if there's anything I should pay more attention to.

Turns out that while I entered this data:
![image](https://github.com/user-attachments/assets/ae21f537-05b5-4f13-949c-6427d640e2fe)

... I don't get the expected results in the json file, under each `uris`, the image field is missing, and the icon looks like this:

> "icon": "undefined/199.png"
![image](https://github.com/user-attachments/assets/8ba2e30c-18cf-4a65-9f10-8de7d248a3c3)

**Comment by mr-zwets** [comment]
Thanks for filing an issue! 🙏 
Just pushed a fix 👍 

since last time you used the generator I restarted the codebase.
The old one was written in vanilla JS and has been moved here:
https://github.com/mr-zwets/bcmr-generator-vanillaJS
